#!/bin/bash
# linear-weekly-pulse.sh — Weekly status pulse: writes local file + posts to Linear CC team
# Runs via OpenClaw cron (Mondays 9:10 AM)
# Reads: Paperclip goals + issues, git log, PM2 health
# Posts: Creates a Linear issue in CC team as a weekly status record

set -euo pipefail

CLAWD="$HOME/clawd"
DATE=$(date +%Y-%m-%d)
DOW=$(date +%A)

# Gather data
echo "=== Linear Weekly Pulse — $DATE ($DOW) ==="

# 1. Paperclip goal progress (port 3100 — canonical)
GOALS=$(curl -s "http://localhost:3100/api/companies/d852cff2-1645-4c48-ae14-010bd8230444/goals" 2>/dev/null || echo "[]")
ISSUES=$(curl -s "http://localhost:3100/api/companies/d852cff2-1645-4c48-ae14-010bd8230444/issues" 2>/dev/null || echo "[]")

PROGRESS=$(python3 -c "
import json, sys
try:
    goals = json.loads('''$GOALS''')
    issues = json.loads('''$ISSUES''')
    from collections import defaultdict
    goal_done = defaultdict(int)
    goal_total = defaultdict(int)
    for i in issues:
        gid = i.get('goalId','')
        if gid:
            goal_total[gid] += 1
            if i.get('status') in ('done','cancelled'):
                goal_done[gid] += 1
    roots = [g for g in goals if not g.get('parentId')]
    for g in roots:
        total = goal_total.get(g['id'],0)
        done = goal_done.get(g['id'],0)
        pct = int(done/total*100) if total > 0 else 0
        print(f'- {g[\"title\"][:40]}: {done}/{total} ({pct}%)')
    if not roots:
        print('- (no goals found or Paperclip unavailable)')
except Exception as e:
    print(f'- (error: {e})')
" 2>/dev/null || echo "- (Paperclip unavailable)")

# 2. Git activity this week
GIT_WEEK=$(cd "$CLAWD" && git log --oneline --since="7 days ago" | wc -l | tr -d ' ')

# 3. PM2 health
PM2_ONLINE=$(pm2 jlist 2>/dev/null | python3 -c "import sys,json; print(sum(1 for p in json.load(sys.stdin) if p['pm2_env']['status']=='online'))" 2>/dev/null || echo "?")

# 4. Gateway status
GW_STATUS=$(openclaw gateway status 2>/dev/null | grep "Runtime:" | head -1 || echo "unknown")

# 5. Paperclip health probe (port 3100 — canonical)
PC_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3100/api/health 2>/dev/null || echo "down")

# 6. Build pulse body
PULSE_BODY="## Weekly Pulse — $DATE ($DOW)

### Goal Progress
$PROGRESS

### Activity
- Git commits this week: $GIT_WEEK
- PM2 services online: $PM2_ONLINE

### Health
- Gateway: $GW_STATUS
- Paperclip: $PC_STATUS

---
*Auto-generated by linear-weekly-pulse.sh*"

# 7. Write pulse to local file
PULSE_DIR="$CLAWD/shared/daily-brief"
mkdir -p "$PULSE_DIR"
PULSE_FILE="$PULSE_DIR/pulse-$DATE.md"
printf "# %s\n\n%s\n" "Weekly Pulse — $DATE" "$PULSE_BODY" > "$PULSE_FILE"
echo "Pulse written to $PULSE_FILE"

# 8. Post to Linear (CC team) as a weekly status issue
LINEAR_API_KEY=$(grep LINEAR_API_KEY_PERSONAL ~/.openclaw/.env | cut -d= -f2 2>/dev/null || echo "")
if [[ -n "$LINEAR_API_KEY" ]]; then
    LINEAR_API_KEY="$LINEAR_API_KEY" ~/bin/linear create "Weekly pulse $DATE" CC "$PULSE_BODY" \
        && echo "Linear issue created for $DATE" \
        || echo "linear post failed: $? (pulse file still written at $PULSE_FILE)"
else
    echo "WARNING: LINEAR_API_KEY_PERSONAL not found in ~/.openclaw/.env — skipping Linear post"
fi

exit 0
